# Generated by Django 5.2.3 on 2025-06-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sintomas', models.TextField()),
                ('data_inicio', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('historico_treinamentos', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField()),
                ('capacidade_carga', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('historico_manutencao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('materiais_necessarios', models.TextField()),
                ('data_registro', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=20)),
                ('data_aquisicao', models.DateField()),
                ('validade', models.DateField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_armazenamento', models.CharField(max_length=100)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fornecedor')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Lavoura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=100)),
                ('variedade', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('data_previsa', models.DateField()),
                ('adubacoes', models.TextField()),
                ('irrigacao', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('responsaveis', models.ManyToManyField(to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Lavoura',
                'verbose_name_plural': 'Lavouras',
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fornecedor')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Transação')),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fornecedor')),
            ],
            options={
                'verbose_name': 'Finança',
                'verbose_name_plural': 'Finanças',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('data_inseminacao', models.DateField(blank=True, null=True)),
                ('peso', models.FloatField()),
                ('raca', models.CharField(max_length=50)),
                ('vacinacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vacina')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
