# Generated by Django 5.2.3 on 2025-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('idade', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('saudavel', 'Saudável'), ('observacao', 'Em observação'), ('tratamento', 'Em tratamento')], default='saudavel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lavoura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_cultura', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_plantio', models.DateField()),
                ('data_colheita', models.DateField(blank=True, null=True)),
                ('produtividade_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('historico_treinamentos', models.TextField(blank=True, null=True, verbose_name='Histórico de Treinamentos')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo', models.CharField(choices=[('Funcionário', 'Funcionário'), ('Fornecedor', 'Fornecedor'), ('Cliente', 'Cliente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(default='Outros', max_length=50)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('tipo_combustivel', models.CharField(blank=True, max_length=50, null=True)),
                ('km_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Disponível', max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
