# Generated by Django 5.2.3 on 2025-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome:')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento:')),
                ('CPF', models.CharField(max_length=11, unique=True, verbose_name='CPF:')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone:')),
                ('email', models.CharField(max_length=70, verbose_name='Email:')),
            ],
        ),
    ]
