# Generated by Django 5.2.3 on 2025-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='status',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('suíno', 'Suíno'), ('Suíno', 'Bovino'), ('Equino', 'Equino'), ('Aves', 'Aves'), ('Caprino', 'Caprino'), ('Coelho', 'Coelho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genero',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(choices=[('D', 'Duroc'), ('G', 'Gilt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='descricao',
            field=models.TextField(max_length=250),
        ),
    ]
