# Generated by Django 5.2.3 on 2025-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transacaofinanceira_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('peso', models.FloatField()),
            ],
        ),
    ]
